from .addUser import addUser
from .getUserIdByUsername import getUserIdByUsername
from .createAccount import createAccount
from .createHistoricalTransaction import createHistoricalTransaction

import json
import multiprocessing


def bulkCreateUsers(namePrefix, numberOfUsers, numberOfTransactions, bankId, seedAccountId, seedBankId, seedAccountCurrency):

    def chunkCreateUsers(i):
        username = namePrefix + str(i)
        password = "aVery4#long" + str(i)
        try:
            addUser((username + "@openbankproject.com"), username, password, "Uli", "Name-" + username)
        except:
            print("User {} not created!".format(username))
        userId = json.loads(getUserIdByUsername(username)).get("user_id")
        print(userId)
        for y in range(1, 6):
            accountId = (str(username) + str(y) + "4bf2-11ea-87e6-54e1adfac5b1")
            createAccount(bankId, userId, "EUR", "autogenerated", "none", "none", accountId)
            for x in range(1, int(numberOfTransactions) + 1):
                createHistoricalTransaction(seedAccountId, seedBankId, accountId, bankId,
                                            seedAccountCurrency, '123',"bulkcreated", '2019-09-19T02:11:29Z', "2019-09-20T02:31:28Z")


    for i in range(1, int(numberOfUsers) + 1):

        p = multiprocessing.Process(target=chunkCreateUsers, args=(i,))
        p.start()











